### ISSUE TITLE
Statery is broken in Next.js

### ISSUE THREAD

**Issue by trezy** [hmans/statery#30]
I tried using Statery in a fresh Next.js app and encountered this error...
```
Error: Missing getServerSnapshot, which is required for server-rendered content. Will revert to client rendering.
```

I've already tracked down the issue: updating to `useSyncExternalStore` (issue #9 and PR #27). More specifically, the issue is that Statery isn't providing a 3rd argument to the hook, [`getServerSnapshot`](https://react.dev/reference/react/useSyncExternalStore#adding-support-for-server-rendering).

Now, React states that this 3rd argument is optional, and _in the error message_ states that it will revert to client rendering. Next.js should be reverting to client rendering for the affected components, but it's not. As a result, this error prevents anything from being loaded at all.

Ideally, this issue should be fixed in Next.js so that nobody encounters it again. I've created [an issue](https://github.com/vercel/next.js/issues/54685) on that repo to track as well, but I expect it'll take quite some time before we see a fix. I'm hoping we can come up with a solution specifically for Statery in the meantime.

FWIW, several other projects have encountered and solved this same issue, so it's not exactly novel. I'll link to a handful of issues/commits where it was discussed/fixed elsewhere.

| Project | Issue | PR or commit |
| - | - | - |
| [Zustand][zustand] | [#886][zustand-issue] | [5a0b40][zustand-commit] |
| [`react-rxjs`][react-rxjs] | [#305][react-rxjs-issue] | [#306][react-rxjs-pr] |
| [Apollo Client][apollo] | [#9623][apollo-issue] | [#9652][apollo-pr] |
| [Amplify UI][amplify-ui] | [#1780][amplify-ui-issue] | [#1798][amplify-ui-pr] |

[amplify-ui]: https://github.com/aws-amplify/amplify-ui
[amplify-ui-issue]: https://github.com/aws-amplify/amplify-ui/issues/1780
[amplify-ui-pr]: https://github.com/aws-amplify/amplify-ui/pull/1798
[apollo]: https://github.com/apollographql/apollo-client
[apollo-issue]: https://github.com/apollographql/apollo-client/issues/9623
[apollo-pr]: https://github.com/apollographql/apollo-client/pull/9652
[react-rxjs]: https://github.com/re-rxjs/react-rxjs
[react-rxjs-issue]: https://github.com/re-rxjs/react-rxjs/issues/305
[react-rxjs-pr]: https://github.com/re-rxjs/react-rxjs/pull/306
[zustand]: https://github.com/pmndrs/zustand
[zustand-issue]: https://github.com/pmndrs/zustand/issues/886
[zustand-commit]: https://github.com/pmndrs/zustand/commit/5a0b404fe7c3ac509636c62b47aa9182c4bddd12

**Comment by trezy** [comment]
Temporary workaround is just to rollback to v0.6.3.

**Comment by hmans** [comment]
Thanks, I'll take a look. I might need a little bit of time until I get around to it as I'm about to start a new job, but I'll try. Thank you very much for the detailed report, and all the extra links to how other projects tackled it.

(Pinging @smartinio, simply because we were discussing this change a while ago and weren't sure what the repercussions would be.)

Anyone encountering this bug, please use version `0.6.3` for now until we figure this out. Thanks!

**Comment by smartinio** [comment]
@hmans Created a PR with a fix and a server-side test. Verified locally that it works as well.

@daveschumaker Feel free to test it on your end too.

**Comment by daveschumaker** [comment]
Nice work! I imported it into my [Next JS v13 app](https://github.com/daveschumaker/artbot-for-stable-diffusion) and it works in both SSR and client contexts. Thanks for tackling this!

**Comment by smartinio** [comment]
Sweet, no worries! Not sure how I ended up tagging you @daveschumaker but I meant to tag the OP @trezy 😅

**Comment by trezy** [comment]
@smartinio Yup, looks great! I tested it locally and it works like a dream. 😁

**Comment by hmans** [comment]
Thanks everyone for jumping in, especially @smartinio for the PR!
