### ISSUE TITLE
Add support for `useSyncExternalStore`

### ISSUE THREAD

**Issue by hmans** [hmans/statery#9]
See: 

- https://www.npmjs.com/package/use-sync-external-store
- https://reactjs.org/docs/hooks-reference.html#usesyncexternalstore
- https://blog.saeloun.com/2021/12/30/react-18-usesyncexternalstore-api

**Comment by smartinio** [comment]
@hmans Hi. Do you mind clarifying the acceptance criteria here? What does "Add support" mean in this context?

**Comment by hmans** [comment]
Thanks for checking in -- I honestly do not have the answer to that question yet! I've only done some superficial research into this hook and had the feeling that it was making assumptions about how the store would work that Statery didn't satisfy, but it's likely I was reading things wrong (or reading the wrong thing.) With the many things going on around React at the moment I at some point made a mental note to revisit this once things settle down a little.

If you're familiar with the hook and/or what newer versions of React expect from store libraries like Statery, any help is appreciated!

**Comment by smartinio** [comment]
@hmans I see. IIUC you want Statery to support doing something like this:

```typescript
const store = makeStore({ someProp: 'foo', otherProp: 'bar' })

function Component() {
  const { someProp } = useSyncExternalStore(store.subscribe, store.getSnapshot)
  ...
}
```

This should be trivial to implement (basically just adding a `getSnapshot` method to the store), however it wouldn't have the `useStore` behavior of only re-rendering if `someProp` changes but not `otherProp`. To get that working, we'd need something more clever. We won't have any control of what happens inside `useSyncExternalStore` so we'd need another way for `store.subscribe` to know which props are of interest. One way would be to have a method that selects a subset of the store with only the props of interest:

```typescript
const store = makeStore({ someProp: 'foo', otherProp: 'bar' })
const subset = store.subset({ only: ['someProp'] })

function Component() {
  const { someProp } = useSyncExternalStore(subset.subscribe, subset.getSnapshot)
  ...
}
```

It's not as elegant as `useStore` since the props would need to be declared "twice". Although TS would at least be able to prevent accessing props in the component that are not part of the subset. WDYT?

**Comment by hmans** [comment]
What would prevent Statery from returning its/a proxy from `store.getSnapshot` (which would keep the library's API intact)?

**Comment by smartinio** [comment]
> What would prevent Statery from returning its/a proxy from store.getSnapshot (which would keep the library's API intact)?

Returning a proxy shouldn't be an issue, but I don't see how we can keep the library's API intact while allowing different components to subscribe to different subsets of props, unless there's something between the store and `useSyncExternalStore` to keep track of that. 

I suppose `store.susbcribe` and `store.getSnapshot` could be tied together by call order, similar to how hooks work under the hood, but it seems brittle and likely a pretty complex undertaking. Idk, maybe I'm missing something obvious that would solve all this.

**Comment by hmans** [comment]
I've re-read the [documentation](https://react.dev/reference/react/useSyncExternalStore) for the hook and still don't fully understand why React expects me (or the user) to use it, and what will break if I (or they) don't. Understanding this better would help me tremendously. I've used Statery in many React apps and have yet to encounter any issues. What is the issue that using this hook fixes?

(To be clear, I'm not at all against implementing support for it, and the frustration that you're likely reading from between the lines is not directed at you in any way. I'm just trying to understand better what it does, why it exists, and why -- or if? -- a library like Statery needs to support or use it, and the official documentation hasn't been of much help.)

**Comment by hmans** [comment]
[This article](https://blog.saeloun.com/2021/12/30/react-18-useSyncExternalStore-api/) gave me a better idea of the problem the hook solves. I'll keep reading and will try to come up with a solution. I'm pretty positive there's something nice we can figure out.

**Comment by smartinio** [comment]
The article works around this with `useCallback` in userland to create a subset of the store scoped to one component instance.

If the idea is to require users to combine `useSyncExternalStore` with `useCallback` then Statery doesn't technically need any changes. It's not very elegant though especially if you want to subscribe to multiple props:

```ts
const store = makeStore({ foo: 1, bar: 2, baz: 3 })

function Component() {
  const subscribe = useCallback((listener: () => void) => {
    store.subscribe(listener)
    return () => store.unsubscribe(listener)
  }, [])

  const foo = useSyncExternalStore(
    subscribe,
    useCallback(() => store.state.foo, [])
  )
  
  const bar = useSyncExternalStore(
    subscribe,
    useCallback(() => store.state.bar, [])
  )
  ...
}
```

> I'll keep reading and will try to come up with a solution

Cool, curious to see what you find!

**Comment by smartinio** [comment]
I shouldn't say userland, because the article encapsulates it in a library-provided `useStore` hook. Statery already has that, though, so this issue becomes a matter of refactoring the internals of the existing `useStore` rather than adding support for the store to be used with `useSyncExternalStore` in userland. Whether that's a necessary refactor at this point I'm not sure.

**Comment by smartinio** [comment]
@hmans I created [a PR](https://github.com/hmans/statery/pull/27) for refactoring the internal hook to use `useSyncExternalStore`. LMK what you think

**Comment by hmans** [comment]
Thanks for the PR - it looks very sane, and I'm very happy that you were able to find an implementation that doesn't require a change of the user-facing API.

I'll give it another more thorough review in a moment and may have some minor remarks, but I'm sure it's all stuff we can figure out.

Other than that, I am still trying to wrap my head around the role of `useSyncExternalStore`. Pretty much by accident I stumbled over [this thread on Twitter](https://twitter.com/tannerlinsley/status/1683530006553833472) that, well, didn't make things easier. This bit raised some red flags:

> uSES is the anti suspense hook - it will always cause a synchronous render to guarantee that an external data source update does not result in tearing of any kind.

I may not fully understand the UI drift issue that this hook is supposed to fix, but wouldn't this only happen with external state that is _mutated_? If so, would Statery even be affected at all (considering that its internal state [always becomes a new object after every update to it](https://github.com/hmans/statery/blob/cc709ea2e5621f265db6ee9753de40e1498c6d15/src/index.ts#L126))?

Just to avoid misunderstandings, my intention with these questions is not to stall the change. I'm just trying to gain a fuller understanding of the issue (and how the hook solves it.) Statements like "useSyncExternalStore is the anti-suspense hook" really make me worry that this sort of change might end up making the library _worse_.

**Comment by smartinio** [comment]
> Just to avoid misunderstandings, my intention with these questions is not to stall the change. I'm just trying to gain a fuller understanding of the issue (and how the hook solves it.) Statements like "useSyncExternalStore is the anti-suspense hook" really make me worry that this sort of change might end up making the library worse.

No worries, these are legitimate concerns and I don't know the inner workings of React enough to provide a good answer. No stress from my side on getting this shipped. Can keep it open until we both understand it better 👍

**Comment by hmans** [comment]
After reading the documentation of `useSyncExternalStore` for what felt like the hundredth time, and closely inspecting its code samples, and thinking about the specific choices they've made for those samples, I'm beginning to understand that the role of `useSyncExternalStore` is primarily

- to make subscribing React components to changes in a _non-React_ store easier (ie. the store is not expected to already come with hooks; `useSyncExternalStore` can take this role. It allows the user to subscribe components to reactive stores that don't know about React.)
- to mitigate the UI drift issue in case the store is updated mid-concurrent-render (or worse, mutated directly) by forcing React out of concurrent mode for trees that use the hook.

I'm still not 100% convinced that the latter has been an issue with Statery (not because I doubt the problem itself, but because there doesn't seem to be a good way to reliably reproduce this sort of drift), but I do enjoy the thought of replacing the slightly annoying `useLayoutEffect` setup this library has had up to now with a primitive provided by React out of the box (your PR is a welcome simplification of the library, and I always enjoy making things simpler.)

So I think what I'd like to do is to push a canary version to NPM built from your PR tomorrow or so, and give that a try in some example sandboxes just to see if things work the way they should, and if things don't suddenly break in terrible and/or unexpected ways, we'll just merge it and see what happens.

So, having said that, thanks for the conversation here and for your PR, I've very much enjoyed this interaction, even if I'm starting to get a little confused by the newest things happening in React, haha.

**Comment by smartinio** [comment]
Sounds good. Likewise! For reference, I managed to track React's internal implementation of `useSyncExternalStore` to [here](https://github.com/facebook/react/blob/main/packages/react-reconciler/src/ReactFiberHooks.js#L1554C15-L1554C15). Might be useful to get an understanding of whether or not your current implementation is better.

**Comment by hmans** [comment]
I've published a version of Statery including the changes in this PR under the `canary` tag, version `0.0.0-canary-20230726060214`.

**Edit:** I've also published [a fork of the demo sandbox that uses this new version](https://codesandbox.io/s/statery-clicker-game-usesyncexternalstore-gfqsls). Things seem fine so far, but the demo is also very simple, and doesn't make use of concurrent React features at all. I'll try to whip something up that specifically uses `useTransition` and/or `<Suspense>` to see how/if they're affected.

**Comment by hmans** [comment]
I've merged the PR and released Statery 0.7.0. Thanks for your input and PR!

**Comment by smartinio** [comment]
@hmans Cool! Did you find anything interesting with respect to concurrent rendering?

**Comment by hmans** [comment]
From what I've gathered, Concurrent React categorically has the problem that it can only reliably update without UI drift if the state originates within React (ie. `useState`), and `useSyncExternalStore` essentially disables any concurrent React features. What this means in practice I'm not 100% sure about, and I'm hoping for feedback from users about this. If this created undesired behavior, I may just roll it back. (But realistically speaking, the user base of this library is _extremely_ small, and the chances of any of its users to be using it in a larger project where the concurrent React features matter is slim, so we'll need to see.)

That aside, I'm happy to what extent the use of the hook simplifies the React hooks this library provides further, so I'm hoping we can keep it.
